### ISSUE TITLE
volume snapshot restore with incorrect crd example

### ISSUE THREAD

**Issue by fengou1** [pingcap/docs-tidb-operator#2165]
## Error Report

for description https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/restore-from-aws-s3-by-snapshot#第-3-步将指定备份数据恢复到-tidb-集群.

```yaml
---
apiVersion: pingcap.com/v1alpha1
kind: Restore
metadata:
  name: demo2-restore-s3
  namespace: test2
spec:
  br:
    cluster: demo2
    clusterNamespace: test2
    backupType: full
    restoreMode: volume-snapshot
    # logLevel: info
  s3:
    provider: aws
    secretName: s3-secret
    region: us-west-1
    bucket: my-bucket
    prefix: my-folder
```

backupType and restoreMode shall be under `spec` not `br`

1. What is the URL/path of the document related to this issue?
 https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/restore-from-aws-s3-by-snapshot#第-3-步将指定备份数据恢复到-tidb-集群.

2. How would you like to improve it?
 
correct the description
