### ISSUE TITLE
There may be an error with the configuration file yaml

### ISSUE THREAD

**Issue by CherryRum** [pingcap/docs-tidb-operator#2398]
File: [/release-1.4/zh/configure-a-tidb-cluster.md](https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/configure-a-tidb-cluster)

```yaml
  pd:
    config: |
      data-dir=/pd/data
      [log.file]
        filename=/pd/log/pd.log
    storageVolumes:
    - name: data
      storageSize: "10Gi"
      mountPath: "/pd/data"
    - name: log
      storageSize: "10Gi"
      mountPath: "/pd/log"
```
May be

```yaml
  pd:
    config: |
      data-dir = "/pd/data"
      [log.file]
        filename = "/pd/log/pd.log"
    storageVolumes:
    - name: data
      storageSize: "10Gi"
      mountPath: "/pd/data"
    - name: log
      storageSize: "10Gi"
      mountPath: "/pd/log"
```

**Comment by Oreoxmt** [comment]
@CherryRum 

- The section under `config` is a block scalar in YAML, which is essentially a multi-line string. The spaces surrounding `=` are optional.

- In this example, `/pd/data` and `/pd/log/pd.log` are interpreted as strings whether they are quoted or not. Quotes are usually needed when a string contains special characters, or when there might be ambiguity between different data types (such as true vs "true"). In this case, since the strings are just paths with `/` characters, they can be unquoted. (refer to https://yaml.org/spec/1.2.2/#733-plain-style)

@csuzhangxc Could you please confirm if my understanding is correct and whether we should modify this example to keep the style consistent with other examples (TiKV and TiDB) in this document?

**Comment by csuzhangxc** [comment]
```toml
      data-dir=/pd/data
      [log.file]
        filename=/pd/log/pd.log
```

This block should be TOML format, so we need to fix it. @CherryRum Thanks for your report!
